name: Build and Release Multi-Platform

on:
  push:
    branches:
      - main

jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]  # Removed Windows
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # -----------------------------
      # Install dependencies
      # -----------------------------
      - name: Install dependencies (Linux)
        if: runner.os == 'Linux'
        run: sudo apt update && sudo apt install -y freeglut3-dev libglew-dev libglu1-mesa-dev

      # -----------------------------
      # Build step for macOS
      # -----------------------------
      - name: Build executable on macOS
        if: runner.os == 'macOS'
        run: |
          clang++ -O2 -std=c++17 -o collatz-visualization-macos collatz-visualization.cpp collatz_modes.cpp -framework GLUT -framework OpenGL
        shell: bash

      # -----------------------------
      # Build step for Linux
      # -----------------------------
      - name: Build executable on Linux
        if: runner.os == 'Linux'
        run: |
          g++ -O2 -std=c++17 -o collatz-visualization-linux collatz-visualization.cpp collatz_modes.cpp -lGL -lGLU -lglut
        shell: bash

      # -----------------------------
      # Upload artifacts
      # -----------------------------
      - name: Upload macOS artifact
        if: runner.os == 'macOS'
        uses: actions/upload-artifact@v4
        with:
          name: collatz-macos
          path: collatz-visualization-macos

      - name: Upload Linux artifact
        if: runner.os == 'Linux'
        uses: actions/upload-artifact@v4
        with:
          name: collatz-linux
          path: collatz-visualization-linux

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download macOS artifact
        uses: actions/download-artifact@v4
        with:
          name: collatz-macos
          path: artifacts/macos

      - name: Download Linux artifact
        uses: actions/download-artifact@v4
        with:
          name: collatz-linux
          path: artifacts/linux

      - name: Create GitHub Release
        uses: ncipollo/release-action@v1
        with:
          tag: v1.0.${{ github.run_number }}
          release_name: Release v1.0.${{ github.run_number }}
          draft: false
          prerelease: false
          artifacts: |
            artifacts/macos/collatz-visualization-macos
            artifacts/linux/collatz-visualization-linux
